apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-counter
  labels:
    release: {{.Release.Name}}
    project: counter
spec:
  ports:
    - port: 80
  selector:
    project: counter
    app: counter
    release: {{.Release.Name}}
