apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-redis
  labels:
    release: {{.Release.Name}}
    project: counter
spec:
  ports:
    - port: 6379
  selector:
    release: {{.Release.Name}}
    project: counter
    app: redis
